
import { Student, AcademicRecord, Activity, ActivityCategory, GithubStats, GithubProject } from './types';
import { PlaceHolderImages } from './placeholder-images';

const studentAvatar = PlaceHolderImages.find(img => img.id === 'student-avatar')?.imageUrl || 'https://picsum.photos/seed/student-avatar/100/100';
const facultyAvatar = PlaceHolderImages.find(img => img.id === 'faculty-avatar')?.imageUrl || 'https://picsum.photos/seed/faculty-avatar/100/100';

export const allSkills = [
  'JavaScript', 'React', 'Node.js', 'Python', 'Data Analysis', 
  'Project Management', 'Public Speaking', 'Team Leadership',
  'TypeScript', 'Java', 'C++', 'AWS', 'Red Hat', 'Linux', 'Marketing', 'UI/UX Design'
];

export const users: Student[] = [
  {
    id: 'STU-001',
    name: 'Tahzeeb',
    email: 'student@gmail.com',
    avatarUrl: studentAvatar,
    major: 'Computer Science',
    year: 3,
    role: 'student',
    githubUsername: 'Tahzeeb-sh0',
    skills: ['TypeScript', 'React', 'Node.js', 'Project Management', 'AWS']
  },
  {
    id: 'FAC-001',
    name: 'Shweta',
    email: 'faculty@gmail.com',
    avatarUrl: facultyAvatar,
    major: 'Computer Science',
    year: 0, 
    role: 'faculty',
  },
   {
    id: 'STU-002',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    avatarUrl: PlaceHolderImages.find(img => img.id === 'student-avatar-2')?.imageUrl,
    major: 'Data Science',
    year: 4,
    role: 'student',
    githubUsername: 'janesmith',
    skills: ['Python', 'Data Analysis', 'React', 'Red Hat', 'Linux']
  },
  {
    id: 'STU-003',
    name: 'Sam Wilson',
    email: 'sam.wilson@example.com',
    avatarUrl: PlaceHolderImages.find(img => img.id === 'student-avatar-3')?.imageUrl,
    major: 'Electrical Engineering',
    year: 2,
    role: 'student',
    skills: ['C++', 'Java', 'AWS', 'Linux']
  },
   {
    id: 'STU-004',
    name: 'Emily Davis',
    email: 'emily.davis@example.com',
    avatarUrl: PlaceHolderImages.find(img => img.id === 'student-avatar-4')?.imageUrl,
    major: 'Business Administration',
    year: 3,
    role: 'student',
    skills: ['Marketing', 'Project Management', 'Public Speaking']
  },
  {
    id: 'STU-005',
    name: 'Michael Brown',
    email: 'michael.brown@example.com',
    avatarUrl: PlaceHolderImages.find(img => img.id === 'student-avatar-5')?.imageUrl,
    major: 'Mechanical Engineering',
    year: 4,
    role: 'student',
    skills: ['Project Management', 'Team Leadership']
  },
  {
    id: 'STU-006',
    name: 'Jessica Garcia',
    email: 'jessica.garcia@example.com',
    avatarUrl: PlaceHolderImages.find(img => img.id === 'student-avatar-6')?.imageUrl,
    major: 'Marketing',
    year: 2,
    role: 'student',
    githubUsername: 'jessgarcia',
    skills: ['Marketing', 'Public Speaking', 'UI/UX Design']
  },
  {
    id: 'STU-007',
    name: 'David Lee',
    email: 'david.lee@example.com',
    avatarUrl: PlaceHolderImages.find(img => img.id === 'student-avatar-7')?.imageUrl,
    major: 'Physics',
    year: 3,
    role: 'student',
    skills: ['Python', 'Data Analysis']
  },
  {
    id: 'STU-008',
    name: 'Sarah Martinez',
    email: 'sarah.martinez@example.com',
    avatarUrl: PlaceHolderImages.find(img => img.id === 'student-avatar-8')?.imageUrl,
    major: 'Biology',
    year: 4,
    role: 'student',
    skills: ['Team Leadership']
  },
];

export const student = users[0]; // Default to Tahzeeb for existing components that rely on a single student
export const facultyUser = users[1];

export const academicRecord: AcademicRecord = {
  gpa: 3.8,
  attendance: 95,
  totalCredits: 120,
  creditsEarned: 85,
};

export const githubStats: GithubStats = {
  repositories: 25,
  commits: 531,
  pullRequests: 42,
  gists: 5,
};

export const activityCategories: ActivityCategory[] = [
    'Conference',
    'Workshop',
    'Certification',
    'Club Activity',
    'Competition',
    'Internship',
    'Community Service',
    'Other',
];

export const githubProjects: GithubProject[] = [
  {
    id: 'PROJ-001',
    name: 'stuverse-app',
    description: 'The very application you are using! A Next.js app for tracking student achievements.',
    url: 'https://github.com/Tahzeeb-sh0/stuverse-app',
    stars: 150,
    forks: 30,
    language: 'TypeScript',
  },
  {
    id: 'PROJ-002',
    name: 'portfolio-generator',
    description: 'A tool to generate a personal portfolio website from a JSON file, built with React.',
    url: 'https://github.com/Tahzeeb-sh0/portfolio-generator',
    stars: 75,
    forks: 12,
    language: 'JavaScript',
  },
  {
    id: 'PROJ-003',
    name: 'genkit-flow-visualizer',
    description: 'A developer tool to visualize and debug Genkit flows in real-time.',
    url: 'https://github.com/Tahzeeb-sh0/genkit-flow-visualizer',
    stars: 200,
    forks: 45,
    language: 'TypeScript',
  },
];

export const activities: Activity[] = [
  {
    id: 'ACT-001',
    studentId: 'STU-001',
    studentName: 'Tahzeeb',
    title: 'Web Development Workshop',
    category: 'Workshop',
    date: new Date('2023-10-15'),
    description: 'A week-long workshop on modern web development technologies.',
    status: 'Approved',
    credits: 2,
  },
  {
    id: 'ACT-002',
    studentId: 'STU-001',
    studentName: 'Tahzeeb',
    title: 'AI in Healthcare Conference',
    category: 'Conference',
    date: new Date('2023-11-05'),
    description: 'Attended the annual conference on Artificial Intelligence applications in the healthcare sector.',
    status: 'Approved',
    credits: 1,
  },
  {
    id: 'ACT-003',
    studentId: 'STU-001',
    studentName: 'Tahzeeb',
    title: 'Summer Internship at TechCorp',
    category: 'Internship',
    date: new Date('2023-08-30'),
    description: 'Completed a 3-month summer internship as a software engineering intern.',
    status: 'Approved',
    credits: 5,
  },
  {
    id: 'ACT-004',
    studentId: 'STU-001',
    studentName: 'Tahzeeb',
    title: 'Hackathon 2023',
    category: 'Competition',
    date: new Date('2023-09-20'),
    description: 'Participated in the university-level hackathon and won 2nd place.',
    status: 'Approved',
    credits: 3,
  },
  {
    id: 'ACT-005',
    studentId: 'STU-001',
    studentName: 'Tahzeeb',
    title: 'Google Cloud Certified',
    category: 'Certification',
    date: new Date('2024-01-10'),
    description: 'Earned the Associate Cloud Engineer certification from Google Cloud.',
    status: 'Pending',
    credits: 4,
  },
  {
    id: 'ACT-006',
    studentId: 'STU-002',
    studentName: 'Jane Smith',
    title: 'Data Science Bootcamp',
    category: 'Workshop',
    date: new Date('2024-02-01'),
    description: 'Intensive bootcamp on data analysis and machine learning.',
    status: 'Approved',
    credits: 3,
  },
    {
    id: 'ACT-007',
    studentId: 'STU-001',
    studentName: 'Tahzeeb',
    title: 'Leadership Role in Coding Club',
    category: 'Club Activity',
    date: new Date('2023-05-20'),
    description: 'Served as the president of the university coding club for the academic year 2022-2023.',
    status: 'Approved',
    credits: 3,
  },
  {
    id: 'ACT-008',
    studentId: 'STU-003',
    studentName: 'Sam Wilson',
    title: 'Community Tree Planting',
    category: 'Community Service',
    date: new Date('2023-04-22'),
    description: 'Volunteered for a local environmental group to plant 100 trees.',
    status: 'Approved',
    credits: 1,
  },
  {
    id: 'ACT-009',
    studentId: 'STU-002',
    studentName: 'Jane Smith',
    title: 'National Design Competition',
    category: 'Competition',
    date: new Date('2024-03-15'),
    description: 'Won first place in the national product design competition.',
    status: 'Approved',
    credits: 5,
  },
  {
    id: 'ACT-010',
    studentId: 'STU-003',
    studentName: 'Sam Wilson',
    title: 'Robotics Club Project Lead',
    category: 'Club Activity',
    date: new Date('2024-04-05'),
    description: 'Led a team to build an autonomous rover for a university showcase.',
    status: 'Approved',
    credits: 3,
  },
   {
    id: 'ACT-011',
    studentId: 'STU-004',
    studentName: 'Emily Davis',
    title: 'Marketing Internship at Adify',
    category: 'Internship',
    date: new Date('2023-12-15'),
    description: 'Managed social media campaigns and analyzed market trends for a startup.',
    status: 'Approved',
    credits: 5,
  },
  {
    id: 'ACT-012',
    studentId: 'STU-002',
    studentName: 'Jane Smith',
    title: 'Published Research Paper',
    category: 'Other',
    date: new Date('2024-05-01'),
    description: 'Co-authored a paper on machine learning models for financial forecasting.',
    status: 'Approved',
    credits: 6,
  },
   {
    id: 'ACT-013',
    studentId: 'STU-004',
    studentName: 'Emily Davis',
    title: 'Business Case Competition',
    category: 'Competition',
    date: new Date('2024-02-20'),
    description: 'Finalist in the inter-university business case competition.',
    status: 'Pending',
    credits: 3,
  },
  {
    id: 'ACT-014',
    studentId: 'STU-002',
    studentName: 'Jane Smith',
    title: 'Red Hat Certified System Administrator (RHCSA)',
    category: 'Certification',
    date: new Date('2024-03-20'),
    description: 'Earned the RHCSA certification, demonstrating core system administration skills for Red Hat Enterprise Linux environments.',
    status: 'Approved',
    credits: 4,
  },
  {
    id: 'ACT-015',
    studentId: 'STU-003',
    studentName: 'Sam Wilson',
    title: 'AWS Certified Solutions Architect - Associate',
    category: 'Certification',
    date: new Date('2024-04-10'),
    description: 'Validated technical expertise in designing and deploying scalable, highly available, and fault-tolerant systems on AWS.',
    status: 'Approved',
    credits: 5,
  },
  {
    id: 'ACT-016',
    studentId: 'STU-005',
    studentName: 'Michael Brown',
    title: 'ASME Design Competition',
    category: 'Competition',
    date: new Date('2023-11-20'),
    description: 'Team lead for a project that won "Most Innovative Design" award.',
    status: 'Approved',
    credits: 4,
  },
  {
    id: 'ACT-017',
    studentId: 'STU-006',
    studentName: 'Jessica Garcia',
    title: 'DECA Chapter President',
    category: 'Club Activity',
    date: new Date('2024-01-15'),
    description: 'Led the university DECA chapter, organizing events and competitions.',
    status: 'Approved',
    credits: 3,
  },
  {
    id: 'ACT-018',
    studentId: 'STU-007',
    studentName: 'David Lee',
    title: 'Undergraduate Research Symposium',
    category: 'Conference',
    date: new Date('2024-04-25'),
    description: 'Presented research on quantum state simulations.',
    status: 'Approved',
    credits: 3,
  },
  {
    id: 'ACT-019',
    studentId: 'STU-008',
    studentName: 'Sarah Martinez',
    title: 'Volunteering at Local Hospital',
    category: 'Community Service',
    date: new Date('2023-12-01'),
    description: 'Completed 100+ hours of volunteer work in the pediatric ward.',
    status: 'Approved',
    credits: 2,
  },
  {
    id: 'ACT-020',
    studentId: 'STU-005',
    studentName: 'Michael Brown',
    title: 'Internship at General Motors',
    category: 'Internship',
    date: new Date('2024-05-10'),
    description: 'Six-month co-op focused on electric vehicle battery design.',
    status: 'Pending',
    credits: 6,
  },
];

    
